net: nemac: Remove unused variable ‘macaddr_dt’
Starting with commit 2de2b7d826 ("ethernet/axxia: simplify and
standardize the usage of of_get_mac_address"), ‘macaddr_dt’
variable is not use anymore and raise error when compiling
with -Werror=unused-variable flag:

drivers/net/ethernet/intel/axxia/nemac.c: In function ‘nemac_probe’:
drivers/net/ethernet/intel/axxia/nemac.c:1251:12: error: unused
   variable ‘macaddr_dt’ [-Werror=unused-variable]

Signed-off-by: Daniel Dragomir <daniel.dragomir@windriver.com>